# Generated by Django 4.1.2 on 2022-10-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Operand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('pnum', models.IntegerField(blank=True, verbose_name='Телефон')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmngr.role', verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('inn', models.IntegerField(blank=True, verbose_name='ИНН')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmngr.location', verbose_name='Местонахождение')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True, verbose_name='Дата создания')),
                ('pay_dock', models.FileField(null=True, upload_to='files/pay_dock/%Y/%m/%d/', verbose_name='Платежка')),
                ('paid_at', models.DateField(null=True, verbose_name='Дата оплаты')),
                ('check_file', models.FileField(null=True, upload_to='files/check_file/%Y/%m/%d/', verbose_name='Счет на оплату')),
                ('total_price', models.IntegerField(blank=True, verbose_name='Сумма')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('agreement', models.BooleanField(blank=True, verbose_name='Согласование')),
                ('agreement_at', models.DateField(null=True, verbose_name='Дата согласования')),
                ('invoice', models.FileField(null=True, upload_to='files/invoice/%Y/%m/%d/', verbose_name='Счет фактура')),
                ('invoice_date', models.DateField(null=True, verbose_name='Дата СФ')),
                ('buh_closed', models.BooleanField(blank=True, verbose_name='Закрыт по БУХ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmngr.user', verbose_name='Автор')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmngr.direction', verbose_name='Направление')),
                ('operand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmngr.operand', verbose_name='Обьект')),
                ('pay_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmngr.pay_status', verbose_name='Статус оплаты')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmngr.plot', verbose_name='Участок')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmngr.provider', verbose_name='Поставщик')),
            ],
        ),
    ]
